// SPDX-License-Identifier: GPL-3.0-or-later

import AppKit
import CoreGraphics
import PerekeyCore

/// "Paste without formatting": puts only the plain text on the pasteboard,
/// posts ⌘V, and puts everything back a moment later.
///
/// Main thread only (the pasteboard is not for the event tap thread). The
/// user's pasteboard is never lost:
/// - the snapshot holds every item with every type, as bytes;
/// - the plain text is marked transient, so clipboard managers skip it;
/// - the snapshot comes back only if nobody wrote to the pasteboard since:
///   a copy the user made in the meantime wins;
/// - a second paste before the restore keeps the first snapshot, since the
///   pasteboard holds Perekey's own text by then.
@MainActor
public final class PlainPaste {
    /// nspasteboard.org conventions: managers like Maccy and Alfred skip these.
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Every item of a pasteboard with every type, as bytes.
    public struct Snapshot: Equatable, Sendable {
        public struct Entry: Equatable, Sendable {
            public var type: String
            public var data: Data
        }

        public var items: [[Entry]]
    }

    private let pasteboard: NSPasteboard
    private let restoreDelay: Duration
    private let post: @MainActor () -> Void
    private var saved: Snapshot?
    /// The change count right after Perekey wrote the plain text.
    private var ownChangeCount = 0
    private var restoreTask: Task<Void, Never>?

    /// - Parameters:
    ///   - pasteboard: `.general` in the app; a named one in tests.
    ///   - restoreDelay: how long the target app gets to read the plain text.
    ///   - post: posts ⌘V (`post(_:)` for the real one).
    public init(pasteboard: NSPasteboard = .general, restoreDelay: Duration = .milliseconds(600),
                post: @escaping @MainActor () -> Void)
    {
        self.pasteboard = pasteboard
        self.restoreDelay = restoreDelay
        self.post = post
    }

    /// Whether a restore is waiting.
    public var isRestorePending: Bool { saved != nil }

    /// Pastes the plain text of the pasteboard. `false` if it holds no text:
    /// nothing is touched then.
    @discardableResult
    public func paste() -> Bool {
        guard let text = Self.plainString(of: pasteboard), !text.isEmpty else { return false }
        // A pending snapshot is still the user's, unless they copied since.
        if saved == nil || pasteboard.changeCount != ownChangeCount {
            saved = Self.snapshot(of: pasteboard)
        }
        ownChangeCount = Self.writePlain(text, to: pasteboard)
        post()
        restoreTask?.cancel()
        restoreTask = Task { [weak self, restoreDelay] in
            try? await Task.sleep(for: restoreDelay)
            guard !Task.isCancelled else { return }
            self?.restoreNow()
        }
        return true
    }

    /// Puts the snapshot back now, if the pasteboard still holds Perekey's text.
    public func restoreNow() {
        restoreTask?.cancel()
        restoreTask = nil
        guard let snapshot = saved else { return }
        saved = nil
        guard pasteboard.changeCount == ownChangeCount else { return }
        Self.restore(snapshot, to: pasteboard)
    }

    // MARK: - Pasteboard

    public static func plainString(of pasteboard: NSPasteboard) -> String? {
        pasteboard.string(forType: .string)
    }

    public static func snapshot(of pasteboard: NSPasteboard) -> Snapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type -> Snapshot.Entry? in
                item.data(forType: type).map { Snapshot.Entry(type: type.rawValue, data: $0) }
            }
        }
        return Snapshot(items: items.filter { !$0.isEmpty })
    }

    /// Replaces the contents with `text` only, marked transient. Returns the new change count.
    @discardableResult
    public static func writePlain(_ text: String, to pasteboard: NSPasteboard) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    @discardableResult
    public static func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard) -> Int {
        pasteboard.clearContents()
        let items = snapshot.items.map { entries in
            let item = NSPasteboardItem()
            for entry in entries { item.setData(entry.data, forType: NSPasteboard.PasteboardType(entry.type)) }
            return item
        }
        if !items.isEmpty { pasteboard.writeObjects(items) }
        return pasteboard.changeCount
    }

    // MARK: - ⌘V

    /// Posts ⌘V on `keyCode`, marked as Perekey's own so the tap lets it through.
    /// `seq` 0 is never a fence's.
    public static func postCommandV(keyCode: UInt16) {
        let source = CGEventSource(stateID: .privateState)
        for down in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: down) else { continue }
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData,
                                       value: SyntheticMark.own(seq: 0, last: !down).userData)
            event.post(tap: .cghidEventTap)
        }
    }
}
